#!/usr/bin/env bash

# envs

TOPLEVEL="$(git rev-parse --show-toplevel)"

# docker network
docker network create bidel

# backend
docker build -t backend-image:latest -f "${TOPLEVEL}"/backend/containerfile "${TOPLEVEL}"/backend
docker run --name ticket-db -d -p 27017:27017 --network bidel -e MONGO_INITDB_ROOT_USERNAME=root -e MONGO_INITDB_ROOT_PASSWORD=password armdocker.rnd.ericsson.se/dockerhub-ericsson-remote/mongo:latest
docker run -dit -p 3000:3000 --network bidel --name backend backend-image:latest

# frontend
docker build -t frontend-image:latest -f "${TOPLEVEL}"/frontend/containerfile "${TOPLEVEL}"/frontend
docker run -dit -p 8080:80 --network bidel --name frontend frontend-image:latest