#!/usr/bin/env bash

# envs

TOPLEVEL="$(git rev-parse --show-toplevel)"

# containers
docker stop backend frontend ticket-db user-db
docker rm backend frontend ticket-db user-db

# images
docker rmi backend-image:latest
docker rmi frontend-image:latest

# docker network
docker network rm bidel
